# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM Dependencies
      run: npm install
    - name: Build Site
      run: npm run build
    - name: Rename Build Folder
      run: |
        rm -rf docs
        mv dist docs
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: docs
